
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install python
          command: |
            sudo apt-get -y install python3-pip
            
      - run:
        name: snapd
        command: |
          sudo snap install docker circleci
          
      - run:
        name: connect
        command: |
          sudo snap connect circleci:docker docker
      
      - run:
          name: install ffsend
          command: |
            sudo snap install ffsend

      - run:
          name: install webtorrent-cli
          command: |
            sudo npm i -g webtorrent-cli
            
      - run:
          name: install zip
          command: |
            sudo apt-get install zip

      - run:
          name: download with webtorrent
          command: |
            webtorrent download "magnet:?xt=urn:btih:C513549AC53FD40FA98D1737A7A9C04FF612E221&dn=Total+Dhamaal+%282019%29+Hindi+720p+HC-HDRip+x264+AAC+-+1.3+GB&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Fshadowshq.yi.org%3A6969%2Fannounce&tr=udp%3A%2F%2Feddie4.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.ch%3A1337%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.grepler.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fpublic.popcorn-tracker.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce"

      - run:
          name: zip file
          command: |
            zip -r ${CIRCLE_BRANCH}.zip ./*
            
      - run:
          name: send file
          command: |
            ffsend -q upload {CIRCLE_BRANCH}.zip | jq --raw-output '.data.file.url.full' | xargs -I {} curl -k -d '{"state":"success","target_url":"{}","context":"sendit"}' -X POST "https://api.github.com/repos/dev-sirvar/sendit/commits/${CIRCLE_SHA1}/statuses?access_token=${GITHUB_TOKEN}"
  
