
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          command: |
            wget https://github.com/timvisee/ffsend/releases/download/v0.2.46/ffsend-v0.2.46-linux-x64
            chmod +x ffsend-v0.2.46-linux-x64
            ./ffsend-v0.2.46-linux-x64 -q upload sendit.sh
