# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install send
          command: |
            sudo pip3 install sendclient

      - run:
          name: install aria2
          command: |
            sudo apt-get install aria2
            
      - run:
          name: install zip
          command: |
            sudo apt-get install zip
      
      - run:
          name: chmod x send file
          command: |
            chmod +x ./sendit.sh
            
      - run:
          name: make temp dir
          command: |
            mkdir temp

      - run:
          name: download with aria2
          command: |
            aria2c -d temp --seed-time=2 --seed-ratio=0.1 'magnet:?xt=urn:btih:E14B6EDF4AF7723D721342576D6CEC96A01C0247&amp;dn=suicide+squad+movie+hd+wallpapers+69+jpg+mixed+res&amp;tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&amp;tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce'

      - run:
          name: zip file
          command: |
            zip -r downloaded.zip temp
            
      - run:
          name: send file
          command: |
            ./sendit.sh downloaded.zip | xargs -I {} curl -k -d "{\"state\":\"success\",\"target_url\":\"{}\",\"context\":\"sendit\"}" -X POST "https://api.github.com/repos/dev-sirvar/sendit/commits/${CIRCLE_SHA1}/statuses?access_token=${GITHUB_TOKEN}"
            
