
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - checkout
            
      - run:
          name: install webtorrent-cli
          command: |
            sudo npm i -g webtorrent-cli

      - run:
          name: install python and node
          command: |
            sudo apt-get -y install python3-pip
            
      - run:
          name: install zip
          command: |
            sudo apt-get install zip

      - run:
          name: download with webtorrent
          command: |
            webtorrent download "magnet:?xt=urn:btih:3F4CCC858F7290CFFC4883D4CCCC7C54F8E8D60A&dn=Total+Dhamal+%282019%29+Hindi+720p+-+WEBHD+-%5Bx264+-+AAC3%286Ch%29%5D%5B1337x%5D&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=http%3A%2F%2F163.172.180.68%3A80%2Fannounce&tr=http%3A%2F%2Ft.nyaatracker.com%2Fannounce&tr=http%3A%2F%2Ftracker.devil-torrents.pl%3A80%2Fannounce&tr=http%3A%2F%2Ftracker.devil-torrents.pl%2Fannounce&tr=http%3A%2F%2Fopen.kickasstracker.com%2Fannounce&tr=http%3A%2F%2F163.172.180.68%2Fannounce&tr=http%3A%2F%2Ft.nyaatracker.com%3A80%2Fannounce&tr=http%3A%2F%2Fretracker.mgts.by%3A80%2Fannounce&tr=http%3A%2F%2F45.33.11.224%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce"

      - run:
          name: zip file
          command: |
            zip -r ${CIRCLE_BRANCH}.zip ./*
            
      - run:
          name: send file
          command: |
            curl --upload-file ./${CIRCLE_BRANCH}.zip https://transfer.sh/${CIRCLE_BRANCH}.zip  | xargs -I {} curl -k -d '{"state":"success","target_url":"{}","context":"sendit"}' -X POST "https://api.github.com/repos/dev-sirvar/sendit/commits/${CIRCLE_SHA1}/statuses?access_token=${GITHUB_TOKEN}"
  
