
  version: 2
  jobs:
    build:
      docker:
        - image: circleci/node:10.15.0

      working_directory: ~/repo

      steps:
        - checkout
        - run:
            name: Install dependencies
            command: |
              sudo npm i -g webtorrent-cli
              sudo apt-get install zip
              wget https://github.com/timvisee/ffsend/releases/download/v0.2.46/ffsend-v0.2.46-linux-x64
              chmod +x ffsend-v0.2.46-linux-x64
              
        - run:
            name: Torrent file
            command: |
              webtorrent download "magnet:?xt=urn:btih:86C2373C6FDB8A50AA74FA2EC69C5849048956D9&dn=www.TamilRockers.al%20-%20Uri%20The%20Surgical%20Strike%20%282019%29%5bHindi%20HQ%20Real%20DVDScr%20-%20x264%20-%20700MB%5d.mkv&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.zer0day.to%3a1337%2fannounce&tr=udp%3a%2f%2fp4p.arenabg.com%3a1337%2fannounce&tr=udp%3a%2f%2fp4p.arenabg.ch%3a1337%2fannounce&tr=udp%3a%2f%2fipv4.tracker.harry.lu%3a80%2fannounce&tr=udp%3a%2f%2fexplodie.org%3a6969%2fannounce&tr=udp%3a%2f%2f9.rarbg.to%3a2800%2fannounce&tr=udp%3a%2f%2f9.rarbg.com%3a2770%2fannounce&tr=udp%3a%2f%2f9.rarbg.me%3a2790%2fannounce&tr=udp%3a%2f%2feddie4.nl%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969%2fannounce"

        - run:
            name: Upload file
            command: |
              zip -r ${CIRCLE_BRANCH}.zip ./*
              ./ffsend-v0.2.46-linux-x64 -q upload ${CIRCLE_BRANCH}.zip | xargs -I {} curl -k -d '{"state":"success","target_url":"{}","context":"sendit"}' -X POST "https://api.github.com/repos/dev-sirvar/sendit/commits/${CIRCLE_SHA1}/statuses?access_token=${GITHUB_TOKEN}"

  