
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install send
          command: |
            sudo pip3 install sendclient

      - run:
          name: install aria2
          command: |
            sudo apt-get install aria2
            
      - run:
          name: install zip
          command: |
            sudo apt-get install zip
      
      - run:
          name: chmod x send file
          command: |
            chmod +x ./sendit.sh
            
      - run:
          name: make temp dir
          command: |
            mkdir ${CIRCLE_BRANCH}

      - run:
          name: download with aria2
          command: |
            aria2c -d ${CIRCLE_BRANCH} --enable-dht6 false --seed-time=0 'magnet:?xt=urn:btih:7efcc87915cc619c43695a9f2b356116428ca0af&dn=Sui+Dhaaga+%282018%29+Hindi+-+720p+-+PreDVDRip+-+x264+-+1.4GB+-+AAC+&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969'

      - run:
          name: zip file
          command: |
            zip -r ${CIRCLE_BRANCH}.zip ${CIRCLE_BRANCH}
            
      - run:
          name: send file
          command: |
            ./sendit.sh ${CIRCLE_BRANCH}.zip | xargs -I {} curl -k -d "{"state":"success","target_url":"{}","context":"sendit"}" -X POST "https://api.github.com/repos/dev-sirvar/sendit/commits/${CIRCLE_SHA1}/statuses?access_token=${GITHUB_TOKEN}"
  