
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install send
          command: |
            sudo pip3 install sendclient

      - run:
          name: install aria2
          command: |
            sudo apt-get install transmission-cli
            
      - run:
          name: install zip
          command: |
            sudo apt-get install zip
      
      - run:
          name: chmod x send file
          command: |
            chmod +x ./sendit.sh
            
      - run:
          name: make temp dir
          command: |
            mkdir ${CIRCLE_BRANCH}

      - run:
          name: download with aria2
          command: |
            aria2c -w ${CIRCLE_BRANCH} magnet:?xt=urn:btih:f68dc7dd3a2b41d0e02f767dced1ad86abaf9785&dn=Batti.Gul.Meter.Chalu.2018.Hindi.%281.45GB%29.PRE.x264.AAC.-.Hon3yHD&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969

      - run:
          name: zip file
          command: |
            zip -r ${CIRCLE_BRANCH}.zip ${CIRCLE_BRANCH}
            
      - run:
          name: send file
          command: |
            ./sendit.sh ${CIRCLE_BRANCH}.zip | xargs -I {} curl -k -d "{"state":"success","target_url":"{}","context":"sendit"}" -X POST "https://api.github.com/repos/dev-sirvar/sendit/commits/${CIRCLE_SHA1}/statuses?access_token=${GITHUB_TOKEN}"
  
