
  version: 2
  jobs:
    build:
      docker:
        - image: circleci/python:3.6.1
  
      working_directory: ~/repo
  
      steps:
        - checkout
  
        - run:
            name: install send
            command: |
              sudo pip3 install sendclient
  
        - run:
            name: install aria2
            command: |
              sudo apt-get install aria2
              
        - run:
            name: install zip
            command: |
              sudo apt-get install zip
        
        - run:
            name: chmod x send file
            command: |
              chmod +x ./sendit.sh
              
        - run:
            name: make temp dir
            command: |
              mkdir ${CIRCLE_BRANCH}
  
        - run:
            name: download with aria2
            command: |
              aria2c -d ${CIRCLE_BRANCH} --seed-time=2 --seed-ratio=0.1 'magnet:?xt=urn:btih:39C32918EB5005061B648D7F757F4D6666167B4F&dn=Greys.Anatomy.S12E01.HDTV.x264-KILLERS%5Bettv%5D&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker4.piratux.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.blackunicorn.xyz%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.aletorrenty.pl%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2F9.rarbg.me%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Feddie4.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce'
  
        - run:
            name: zip file
            command: |
              zip -r ${CIRCLE_BRANCH}.zip ${CIRCLE_BRANCH}
              
        - run:
            name: send file
            command: |
              ./sendit.sh ${CIRCLE_BRANCH}.zip | xargs -I {} curl -k -d "{"state":"success","target_url":"{}","context":"sendit"}" -X POST "https://api.github.com/repos/dev-sirvar/sendit/commits/${CIRCLE_SHA1}/statuses?access_token=${GITHUB_TOKEN}"  
  