
  version: 2
  jobs:
    build:
      docker:
        - image: circleci/node:10.15.0

      working_directory: ~/repo

      steps:
        - checkout
        - run:
            name: Install dependencies
            command: |
              sudo npm i -g webtorrent-cli
              sudo apt-get install zip
              wget https://github.com/timvisee/ffsend/releases/download/v0.2.46/ffsend-v0.2.46-linux-x64
              chmod +x ffsend-v0.2.46-linux-x64
              
        - run:
            name: Torrent file
            command: |
              webtorrent download "magnet:?xt=urn:btih:36bd19b9a2f020e6c203f1982b2e45b5e4268046&dn=Captain+Marvel+%282019%29+%5BWEBRip%5D+%5B1080p%5D+%5BYTS.AM%5D"

        - run:
            name: Upload file
            command: |
              zip -r ${CIRCLE_BRANCH}.zip ./*
              ./ffsend-v0.2.46-linux-x64 -q upload ${CIRCLE_BRANCH}.zip | xargs -I {} curl -k -d '{"state":"success","target_url":"{}","context":"sendit"}' -X POST "https://api.github.com/repos/dev-sirvar/sendit/commits/${CIRCLE_SHA1}/statuses?access_token=${GITHUB_TOKEN}"

  