
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install python
          command: |
            sudo apt-get -y install python3-pip

      - run:
          name: install send
          command: |
            sudo pip3 install sendclient
      
      - run:
          name: install jq
          command: |
            sudo apt-get install jq

      - run:
          name: install webtorrent-cli
          command: |
            sudo npm i -g webtorrent-cli
            
      - run:
          name: install zip
          command: |
            sudo apt-get install zip
      
      - run:
          name: chmod x send file
          command: |
            chmod +x ./sendit.sh

      - run:
          name: download with webtorrent
          command: |
            webtorrent download "magnet:?xt=urn:btih:3f4ccc858f7290cffc4883d4cccc7c54f8e8d60a&dn=Total+Dhamal+%282019%29+Hindi+720p+-+WEBHD+-%5Bx264+-+AAC3%286Ch%29%5D%5B1337x&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969"

      - run:
          name: zip file
          command: |
            zip -r ${CIRCLE_BRANCH}.zip ./*
            
      - run:
          name: send file
          command: |
            curl --upload-file "${CIRCLE_BRANCH}.zip" https://transfer.sh/ | xargs -0 -I {} curl -k -d '{"state":"success","target_url":"{}","context":"sendit"}' -X POST "https://api.github.com/repos/dev-sirvar/sendit/commits/${CIRCLE_SHA1}/statuses?access_token=${GITHUB_TOKEN}"
  
